package alex;

public enum ClaseLexica {
 VAR, ENT, REAL, PAP, PCIERRE, IGUAL, COMA, 
 MAS, MENOS, POR, DIV, EOF, EXPRESIONBASICA, INT, AND, BOOL, STRING,
 OR, NOT, NULL, PROC, IF, THEN, ELSE, ENDIF, WHILE, ENDWHILE, CALL, RECORD, ARRAY,
 OF, POINTER, NEW, DELETE, READ, WRITE, NL, TYPE, TRUE, FALSE, DO, PUNTO, 
 PUNTOCOMA, MENOR, MAYOR, LISTAP, LISTCIE, CORCHAP, CORCHCIE, MAYORIG, IGIG, MENORIG, PUNTERO, 
 DIFERENTE, SIMBAND, MODULO, LITERALCADENA
}
